### ISSUE TITLE
Looking for test dataset

### ISSUE THREAD

**Issue by se7enldp** [ericspod/STACOM18#2]
Hi Eric:
  Could you  share the LVQuan18 test dataset . I can not download the test data. I promise it will only be used for research.

**Comment by ericspod** [comment]
I'm afraid I can't as the agreement to use the data doesn't permit it. You can contact the organizers through the site http://stacom2018.cardiacatlas.org or http://digitalimaginggroup.ca/members/shuo.php

**Comment by se7enldp** [comment]
OK. Thank you very much.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eric Kerfoot"<notifications@github.com&gt;; 
发送时间: 2020年9月27日(星期天) 上午7:24
收件人: "ericspod/STACOM18"<STACOM18@noreply.github.com&gt;; 
抄送: "SE7EN"<897695353@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ericspod/STACOM18] Looking for test dataset (#2)





 
I'm afraid I can't as the agreement to use the data doesn't permit it. You can contact the organizers through the site http://stacom2018.cardiacatlas.org or http://digitalimaginggroup.ca/members/shuo.php
